In [1]:
import pandas as pd

In [2]:
blue_data = pd.read_csv("Blue_whales_North.csv")

In [3]:
blue1 = blue_data[blue_data["individualID"].str.contains("2005CA-Bmu-01390")]
print(len(blue1))

285

In [4]:
blue2 = blue_data[blue_data["individualID"].str.contains("2005CA-Bmu-02082")]
print(len(blue2))

26

In [5]:
blue3 = blue_data[blue_data["individualID"].str.contains("2005CA-Bmu-00845")]
print(len(blue3))

46

In [6]:
blue4 = blue_data[blue_data["individualID"].str.contains("2005CA-Bmu-01388")]
print(len(blue4))

75

In [7]:
all_blue = [blue1, blue2, blue3, blue4]

In [8]:
blue_whale_124 = pd.concat(all_blue)
blue_whale_124

,event-id,visible,timestamp,long,lat,argos:best-level,argos:calcul-freq,argos:iq,argos:lat1,argos:lat2,...,argos:lon1,argos:lon2,argos:nb-mes,argos:nb-mes-120,manually-marked-outlier,sensor-type,individual-taxon-canonical-name,tag-local-identifier,individualID,study-name
94,9018011315,True,12:00.0,-122.015,36.668,NaN,NaN,NaN,36.668,NaN,...,-122.015,NaN,NaN,NaN,NaN,gps,Balaenoptera musculus,2005CA-ST15-01390,2005CA-Bmu-01390,Blue whales Eastern North Pacific 1993-2008 - ...
8679,9018020238,True,20:36.0,-122.032,36.657,-136.0,649841.31,0.0,36.657,26.607,...,-122.032,-171.398,2.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01390,2005CA-Bmu-01390,Blue whales Eastern North Pacific 1993-2008 - ...
8680,9018020239,True,52:41.0,-121.947,36.707,-133.0,649824.81,60.0,36.707,28.309,...,-121.947,-162.372,4.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01390,2005CA-Bmu-01390,Blue whales Eastern North Pacific 1993-2008 - ...
8681,9018020240,True,59:26.0,-122.406,36.715,-128.0,649841.31,0.0,36.715,35.262,...,-122.406,-129.196,2.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01390,2005CA-Bmu-01390,Blue whales Eastern North Pacific 1993-2008 - ...
8682,9018020241,False,17:08.0,-121.766,36.809,-130.0,649841.31,0.0,36.809,42.244,...,-121.766,-147.640,2.0,0.0,True,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01390,2005CA-Bmu-01390,Blue whales Eastern North Pacific 1993-2008 - ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8549,9018020108,True,55:40.0,-122.563,35.198,-134.0,651157.87,0.0,35.198,25.938,...,-122.563,-77.024,2.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01388,2005CA-Bmu-01388,Blue whales Eastern North Pacific 1993-2008 - ...
8550,9018020109,True,59:31.0,-123.653,35.355,-129.0,651157.87,10.0,35.355,33.988,...,-123.653,-128.349,5.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01388,2005CA-Bmu-01388,Blue whales Eastern North Pacific 1993-2008 - ...
8551,9018020110,True,01:50.0,-122.310,35.234,-134.0,651157.87,0.0,35.234,44.149,...,-122.310,-167.533,2.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01388,2005CA-Bmu-01388,Blue whales Eastern North Pacific 1993-2008 - ...
8552,9018020111,True,50:31.0,-122.307,35.315,-129.0,651215.68,60.0,35.315,43.106,...,-122.307,-160.797,4.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01388,2005CA-Bmu-01388,Blue whales Eastern North Pacific 1993-2008 - ...
8553,9018020112,True,03:35.0,-121.931,35.357,-129.0,651157.87,0.0,35.357,32.183,...,-121.931,-137.438,2.0,0.0,NaN,argos-doppler-shift,Balaenoptera musculus,2005CA-ST15-01388,2005CA-Bmu-01388,Blue whales Eastern North Pacific 1993-2008 - ...

In [9]:
blue_whale_124.to_csv(r'Blue_whale.csv', index = False, header = True)